// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { activate, addMedicalRecord, addTimeSlots, cancelVisit, createStaff, deactivateStaff, deleteStaff, getAvailableSlots, getMedicalHistory, getMedicalRecordByVisitId, getPatientProfile, getScheduleByDoctor, getStaff, getVisitsByDoctor, getVisitsByPatient, listDoctors, listStaff, login, logout, type Options, register, removeSlot, reserveVisit, searchPatients, searchStaff, updateMedicalRecord, updatePersonalData, updateSlot, updateStaff } from '../sdk.gen';
import type { ActivateData, AddMedicalRecordData, AddTimeSlotsData, CancelVisitData, CreateStaffData, CreateStaffResponse, DeactivateStaffData, DeleteStaffData, GetAvailableSlotsData, GetAvailableSlotsResponse, GetMedicalHistoryData, GetMedicalHistoryResponse, GetMedicalRecordByVisitIdData, GetMedicalRecordByVisitIdResponse, GetPatientProfileData, GetPatientProfileResponse, GetScheduleByDoctorData, GetScheduleByDoctorResponse, GetStaffData, GetStaffResponse, GetVisitsByDoctorData, GetVisitsByDoctorResponse, GetVisitsByPatientData, GetVisitsByPatientResponse, ListDoctorsData, ListDoctorsResponse, ListStaffData, ListStaffResponse, LoginData, LoginResponse, LogoutData, RegisterData, RegisterResponse, RemoveSlotData, ReserveVisitData, ReserveVisitResponse, SearchPatientsData, SearchPatientsResponse, SearchStaffData, SearchStaffResponse, UpdateMedicalRecordData, UpdatePersonalDataData, UpdatePersonalDataResponse, UpdateSlotData, UpdateStaffData } from '../types.gen';

export const deleteStaffMutation = (options?: Partial<Options<DeleteStaffData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteStaffData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteStaffData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteStaff({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getStaffQueryKey = (options: Options<GetStaffData>) => createQueryKey('getStaff', options);

export const getStaffOptions = (options: Options<GetStaffData>) => queryOptions<GetStaffResponse, DefaultError, GetStaffResponse, ReturnType<typeof getStaffQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStaff({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStaffQueryKey(options)
});

export const updateStaffMutation = (options?: Partial<Options<UpdateStaffData>>): UseMutationOptions<unknown, DefaultError, Options<UpdateStaffData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<UpdateStaffData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateStaff({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const removeSlotMutation = (options?: Partial<Options<RemoveSlotData>>): UseMutationOptions<unknown, DefaultError, Options<RemoveSlotData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<RemoveSlotData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await removeSlot({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const updateSlotMutation = (options?: Partial<Options<UpdateSlotData>>): UseMutationOptions<unknown, DefaultError, Options<UpdateSlotData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<UpdateSlotData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateSlot({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPatientProfileQueryKey = (options: Options<GetPatientProfileData>) => createQueryKey('getPatientProfile', options);

export const getPatientProfileOptions = (options: Options<GetPatientProfileData>) => queryOptions<GetPatientProfileResponse, DefaultError, GetPatientProfileResponse, ReturnType<typeof getPatientProfileQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPatientProfile({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPatientProfileQueryKey(options)
});

export const updatePersonalDataMutation = (options?: Partial<Options<UpdatePersonalDataData>>): UseMutationOptions<UpdatePersonalDataResponse, DefaultError, Options<UpdatePersonalDataData>> => {
    const mutationOptions: UseMutationOptions<UpdatePersonalDataResponse, DefaultError, Options<UpdatePersonalDataData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updatePersonalData({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const updateMedicalRecordMutation = (options?: Partial<Options<UpdateMedicalRecordData>>): UseMutationOptions<unknown, DefaultError, Options<UpdateMedicalRecordData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<UpdateMedicalRecordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateMedicalRecord({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const reserveVisitMutation = (options?: Partial<Options<ReserveVisitData>>): UseMutationOptions<ReserveVisitResponse, DefaultError, Options<ReserveVisitData>> => {
    const mutationOptions: UseMutationOptions<ReserveVisitResponse, DefaultError, Options<ReserveVisitData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await reserveVisit({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const cancelVisitMutation = (options?: Partial<Options<CancelVisitData>>): UseMutationOptions<unknown, DefaultError, Options<CancelVisitData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<CancelVisitData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await cancelVisit({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listStaffQueryKey = (options?: Options<ListStaffData>) => createQueryKey('listStaff', options);

export const listStaffOptions = (options?: Options<ListStaffData>) => queryOptions<ListStaffResponse, DefaultError, ListStaffResponse, ReturnType<typeof listStaffQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listStaff({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listStaffQueryKey(options)
});

export const createStaffMutation = (options?: Partial<Options<CreateStaffData>>): UseMutationOptions<CreateStaffResponse, DefaultError, Options<CreateStaffData>> => {
    const mutationOptions: UseMutationOptions<CreateStaffResponse, DefaultError, Options<CreateStaffData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createStaff({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deactivateStaffMutation = (options?: Partial<Options<DeactivateStaffData>>): UseMutationOptions<unknown, DefaultError, Options<DeactivateStaffData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeactivateStaffData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deactivateStaff({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const addTimeSlotsMutation = (options?: Partial<Options<AddTimeSlotsData>>): UseMutationOptions<unknown, DefaultError, Options<AddTimeSlotsData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AddTimeSlotsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addTimeSlots({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getMedicalHistoryQueryKey = (options: Options<GetMedicalHistoryData>) => createQueryKey('getMedicalHistory', options);

export const getMedicalHistoryOptions = (options: Options<GetMedicalHistoryData>) => queryOptions<GetMedicalHistoryResponse, DefaultError, GetMedicalHistoryResponse, ReturnType<typeof getMedicalHistoryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMedicalHistory({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMedicalHistoryQueryKey(options)
});

export const addMedicalRecordMutation = (options?: Partial<Options<AddMedicalRecordData>>): UseMutationOptions<unknown, DefaultError, Options<AddMedicalRecordData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AddMedicalRecordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addMedicalRecord({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const registerMutation = (options?: Partial<Options<RegisterData>>): UseMutationOptions<RegisterResponse, DefaultError, Options<RegisterData>> => {
    const mutationOptions: UseMutationOptions<RegisterResponse, DefaultError, Options<RegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await register({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<unknown, DefaultError, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse, DefaultError, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse, DefaultError, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getVisitsByPatientQueryKey = (options: Options<GetVisitsByPatientData>) => createQueryKey('getVisitsByPatient', options);

export const getVisitsByPatientOptions = (options: Options<GetVisitsByPatientData>) => queryOptions<GetVisitsByPatientResponse, DefaultError, GetVisitsByPatientResponse, ReturnType<typeof getVisitsByPatientQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getVisitsByPatient({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getVisitsByPatientQueryKey(options)
});

export const getVisitsByDoctorQueryKey = (options: Options<GetVisitsByDoctorData>) => createQueryKey('getVisitsByDoctor', options);

export const getVisitsByDoctorOptions = (options: Options<GetVisitsByDoctorData>) => queryOptions<GetVisitsByDoctorResponse, DefaultError, GetVisitsByDoctorResponse, ReturnType<typeof getVisitsByDoctorQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getVisitsByDoctor({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getVisitsByDoctorQueryKey(options)
});

export const searchStaffQueryKey = (options?: Options<SearchStaffData>) => createQueryKey('searchStaff', options);

export const searchStaffOptions = (options?: Options<SearchStaffData>) => queryOptions<SearchStaffResponse, DefaultError, SearchStaffResponse, ReturnType<typeof searchStaffQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await searchStaff({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: searchStaffQueryKey(options)
});

export const getScheduleByDoctorQueryKey = (options: Options<GetScheduleByDoctorData>) => createQueryKey('getScheduleByDoctor', options);

export const getScheduleByDoctorOptions = (options: Options<GetScheduleByDoctorData>) => queryOptions<GetScheduleByDoctorResponse, DefaultError, GetScheduleByDoctorResponse, ReturnType<typeof getScheduleByDoctorQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getScheduleByDoctor({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getScheduleByDoctorQueryKey(options)
});

export const getAvailableSlotsQueryKey = (options?: Options<GetAvailableSlotsData>) => createQueryKey('getAvailableSlots', options);

export const getAvailableSlotsOptions = (options?: Options<GetAvailableSlotsData>) => queryOptions<GetAvailableSlotsResponse, DefaultError, GetAvailableSlotsResponse, ReturnType<typeof getAvailableSlotsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAvailableSlots({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAvailableSlotsQueryKey(options)
});

export const getMedicalRecordByVisitIdQueryKey = (options: Options<GetMedicalRecordByVisitIdData>) => createQueryKey('getMedicalRecordByVisitId', options);

export const getMedicalRecordByVisitIdOptions = (options: Options<GetMedicalRecordByVisitIdData>) => queryOptions<GetMedicalRecordByVisitIdResponse, DefaultError, GetMedicalRecordByVisitIdResponse, ReturnType<typeof getMedicalRecordByVisitIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMedicalRecordByVisitId({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMedicalRecordByVisitIdQueryKey(options)
});

export const searchPatientsQueryKey = (options?: Options<SearchPatientsData>) => createQueryKey('searchPatients', options);

export const searchPatientsOptions = (options?: Options<SearchPatientsData>) => queryOptions<SearchPatientsResponse, DefaultError, SearchPatientsResponse, ReturnType<typeof searchPatientsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await searchPatients({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: searchPatientsQueryKey(options)
});

export const listDoctorsQueryKey = (options?: Options<ListDoctorsData>) => createQueryKey('listDoctors', options);

export const listDoctorsOptions = (options?: Options<ListDoctorsData>) => queryOptions<ListDoctorsResponse, DefaultError, ListDoctorsResponse, ReturnType<typeof listDoctorsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listDoctors({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listDoctorsQueryKey(options)
});

export const activateQueryKey = (options: Options<ActivateData>) => createQueryKey('activate', options);

export const activateOptions = (options: Options<ActivateData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof activateQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await activate({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: activateQueryKey(options)
});
