// This file is auto-generated by @hey-api/openapi-ts

export const UpdateStaffCommandSchema = {
    type: 'object',
    properties: {
        firstName: {
            type: 'string',
            minLength: 1
        },
        lastName: {
            type: 'string',
            minLength: 1
        },
        email: {
            type: 'string',
            minLength: 1
        },
        active: {
            type: 'boolean'
        },
        specialization: {
            type: 'string'
        },
        pwz: {
            type: 'string',
            pattern: '^[1-9]\\d{6}$'
        },
        department: {
            type: 'string'
        },
        position: {
            type: 'string'
        },
        workSchedule: {
            type: 'string'
        }
    }
} as const;

export const TimeRangeSchema = {
    type: 'object',
    properties: {
        startTime: {
            type: 'string',
            format: 'date-time'
        },
        endTime: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const UpdateSlotRequestSchema = {
    type: 'object',
    properties: {
        timeRange: {
            $ref: '#/components/schemas/TimeRange'
        },
        office: {
            type: 'string'
        }
    }
} as const;

export const UpdatePersonalDataReqSchema = {
    type: 'object',
    properties: {
        firstName: {
            type: 'string',
            minLength: 1
        },
        lastName: {
            type: 'string',
            minLength: 1
        },
        phone: {
            type: 'string',
            minLength: 1
        },
        email: {
            type: 'string',
            minLength: 1
        },
        address: {
            type: 'string'
        }
    }
} as const;

export const UpdateMedicalRecordReqSchema = {
    type: 'object',
    properties: {
        diagnoses: {
            type: 'string',
            minLength: 1
        },
        symptoms: {
            type: 'string'
        },
        prescriptions: {
            type: 'string'
        },
        notes: {
            type: 'string'
        },
        testResults: {
            type: 'string'
        }
    }
} as const;

export const ReserveVisitRequestSchema = {
    type: 'object',
    properties: {
        patientId: {
            type: 'string',
            format: 'uuid'
        },
        doctorId: {
            type: 'string',
            format: 'uuid'
        },
        type: {
            type: 'string',
            enum: [
                'GENERAL',
                'SPECIALIST',
                'FOLLOW_UP'
            ]
        },
        slotIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const CreateStaffCommandSchema = {
    type: 'object',
    properties: {
        role: {
            type: 'string',
            enum: [
                'DOCTOR',
                'ADMIN_STAFF'
            ]
        },
        firstName: {
            type: 'string',
            minLength: 1
        },
        lastName: {
            type: 'string',
            minLength: 1
        },
        email: {
            type: 'string',
            minLength: 1
        },
        specialization: {
            type: 'string'
        },
        pwz: {
            type: 'string',
            pattern: '^[1-9]\\d{6}$'
        },
        department: {
            type: 'string'
        },
        position: {
            type: 'string'
        },
        workSchedule: {
            type: 'string'
        }
    },
    required: [
        'role'
    ]
} as const;

export const AddSlotCommandSchema = {
    type: 'object',
    properties: {
        timeRange: {
            $ref: '#/components/schemas/TimeRange'
        },
        office: {
            type: 'string'
        }
    }
} as const;

export const AddSlotsRequestSchema = {
    type: 'object',
    properties: {
        commands: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/AddSlotCommand'
            }
        }
    }
} as const;

export const AddMedicalRecordReqSchema = {
    type: 'object',
    properties: {
        visitId: {
            type: 'string',
            format: 'uuid'
        },
        doctorId: {
            type: 'string',
            format: 'uuid'
        },
        diagnoses: {
            type: 'string',
            minLength: 1
        },
        symptoms: {
            type: 'string'
        },
        prescriptions: {
            type: 'string'
        },
        notes: {
            type: 'string'
        },
        testResults: {
            type: 'string'
        }
    }
} as const;

export const RegisterReqSchema = {
    type: 'object',
    properties: {
        firstName: {
            type: 'string',
            minLength: 1
        },
        lastName: {
            type: 'string',
            minLength: 1
        },
        pesel: {
            type: 'string',
            minLength: 1
        },
        phone: {
            type: 'string',
            minLength: 1
        },
        email: {
            type: 'string',
            minLength: 1
        },
        password: {
            type: 'string',
            minLength: 1
        }
    }
} as const;

export const LoginRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    }
} as const;

export const AuthResultSchema = {
    type: 'object',
    properties: {
        userId: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        role: {
            type: 'string'
        },
        accessToken: {
            type: 'string'
        }
    }
} as const;

export const VisitDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        date: {
            type: 'string'
        },
        doctorId: {
            type: 'string',
            format: 'uuid'
        },
        doctorName: {
            type: 'string'
        },
        patientId: {
            type: 'string',
            format: 'uuid'
        },
        patientName: {
            type: 'string'
        },
        status: {
            type: 'string'
        },
        type: {
            type: 'string'
        },
        room: {
            type: 'string'
        }
    }
} as const;

export const StaffDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        role: {
            type: 'string'
        },
        firstName: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        active: {
            type: 'boolean'
        },
        specialization: {
            type: 'string'
        },
        pwz: {
            type: 'string'
        },
        department: {
            type: 'string'
        },
        position: {
            type: 'string'
        },
        workSchedule: {
            type: 'string'
        }
    }
} as const;

export const ScheduleDtoSchema = {
    type: 'object',
    properties: {
        scheduleId: {
            type: 'string',
            format: 'uuid'
        },
        doctorId: {
            type: 'string',
            format: 'uuid'
        },
        slots: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/SlotDto'
            }
        }
    }
} as const;

export const SlotDtoSchema = {
    type: 'object',
    properties: {
        slotId: {
            type: 'string',
            format: 'uuid'
        },
        timeRange: {
            $ref: '#/components/schemas/TimeRange'
        },
        office: {
            type: 'string'
        },
        status: {
            type: 'string'
        }
    }
} as const;

export const AvailableSlotDtoSchema = {
    type: 'object',
    properties: {
        slotId: {
            type: 'string',
            format: 'uuid'
        },
        doctorId: {
            type: 'string',
            format: 'uuid'
        },
        doctorFirstName: {
            type: 'string'
        },
        doctorLastName: {
            type: 'string'
        },
        specialization: {
            type: 'string'
        },
        startTime: {
            type: 'string',
            format: 'date-time'
        },
        endTime: {
            type: 'string',
            format: 'date-time'
        },
        office: {
            type: 'string'
        }
    }
} as const;

export const DoctorIdSchema = {
    type: 'object',
    properties: {
        value: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const MedicalRecordSchema = {
    type: 'object',
    properties: {
        recordId: {
            type: 'string',
            format: 'uuid'
        },
        visitId: {
            type: 'string',
            format: 'uuid'
        },
        doctorId: {
            $ref: '#/components/schemas/DoctorId'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        diagnoses: {
            type: 'string'
        },
        symptoms: {
            type: 'string'
        },
        prescriptions: {
            type: 'string'
        },
        notes: {
            type: 'string'
        },
        testResults: {
            type: 'string'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedBy: {
            $ref: '#/components/schemas/DoctorId'
        }
    }
} as const;

export const PatientSchema = {
    type: 'object',
    properties: {
        id: {
            $ref: '#/components/schemas/PatientId'
        },
        pesel: {
            type: 'string'
        },
        medicalRecords: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/MedicalRecord'
            }
        },
        firstName: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        phone: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        address: {
            type: 'string'
        }
    }
} as const;

export const PatientIdSchema = {
    type: 'object',
    properties: {
        value: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;
