// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ActivateData, ActivateResponses, AddMedicalRecordData, AddMedicalRecordResponses, AddTimeSlotsData, AddTimeSlotsResponses, CancelVisitData, CancelVisitResponses, CreateStaffData, CreateStaffResponses, DeactivateStaffData, DeactivateStaffResponses, DeleteStaffData, DeleteStaffResponses, GetAvailableSlotsData, GetAvailableSlotsResponses, GetMedicalHistoryData, GetMedicalHistoryResponses, GetMedicalRecordByVisitIdData, GetMedicalRecordByVisitIdResponses, GetPatientProfileData, GetPatientProfileResponses, GetScheduleByDoctorData, GetScheduleByDoctorResponses, GetStaffData, GetStaffResponses, GetVisitsByDoctorData, GetVisitsByDoctorResponses, GetVisitsByPatientData, GetVisitsByPatientResponses, ListDoctorsData, ListDoctorsResponses, ListStaffData, ListStaffResponses, LoginData, LoginResponses, LogoutData, LogoutResponses, RegisterData, RegisterResponses, RemoveSlotData, RemoveSlotResponses, ReserveVisitData, ReserveVisitResponses, SearchPatientsData, SearchPatientsResponses, SearchStaffData, SearchStaffResponses, UpdateMedicalRecordData, UpdateMedicalRecordResponses, UpdatePersonalDataData, UpdatePersonalDataResponses, UpdateSlotData, UpdateSlotResponses, UpdateStaffData, UpdateStaffResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const deleteStaff = <ThrowOnError extends boolean = false>(options: Options<DeleteStaffData, ThrowOnError>): RequestResult<DeleteStaffResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteStaffResponses, unknown, ThrowOnError>({ url: '/api/staff/{id}', ...options });

export const getStaff = <ThrowOnError extends boolean = false>(options: Options<GetStaffData, ThrowOnError>): RequestResult<GetStaffResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetStaffResponses, unknown, ThrowOnError>({ url: '/api/staff/{id}', ...options });

export const updateStaff = <ThrowOnError extends boolean = false>(options: Options<UpdateStaffData, ThrowOnError>): RequestResult<UpdateStaffResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateStaffResponses, unknown, ThrowOnError>({
    url: '/api/staff/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const removeSlot = <ThrowOnError extends boolean = false>(options: Options<RemoveSlotData, ThrowOnError>): RequestResult<RemoveSlotResponses, unknown, ThrowOnError> => (options.client ?? client).delete<RemoveSlotResponses, unknown, ThrowOnError>({ url: '/api/schedules/{doctorId}/slots/{slotId}', ...options });

export const updateSlot = <ThrowOnError extends boolean = false>(options: Options<UpdateSlotData, ThrowOnError>): RequestResult<UpdateSlotResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateSlotResponses, unknown, ThrowOnError>({
    url: '/api/schedules/{doctorId}/slots/{slotId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getPatientProfile = <ThrowOnError extends boolean = false>(options: Options<GetPatientProfileData, ThrowOnError>): RequestResult<GetPatientProfileResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetPatientProfileResponses, unknown, ThrowOnError>({ url: '/api/patients/{patientId}', ...options });

export const updatePersonalData = <ThrowOnError extends boolean = false>(options: Options<UpdatePersonalDataData, ThrowOnError>): RequestResult<UpdatePersonalDataResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdatePersonalDataResponses, unknown, ThrowOnError>({
    url: '/api/patients/{patientId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const updateMedicalRecord = <ThrowOnError extends boolean = false>(options: Options<UpdateMedicalRecordData, ThrowOnError>): RequestResult<UpdateMedicalRecordResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateMedicalRecordResponses, unknown, ThrowOnError>({
    url: '/api/patients/{patientId}/medical-records/{recordId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const reserveVisit = <ThrowOnError extends boolean = false>(options: Options<ReserveVisitData, ThrowOnError>): RequestResult<ReserveVisitResponses, unknown, ThrowOnError> => (options.client ?? client).post<ReserveVisitResponses, unknown, ThrowOnError>({
    url: '/api/visits',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const cancelVisit = <ThrowOnError extends boolean = false>(options: Options<CancelVisitData, ThrowOnError>): RequestResult<CancelVisitResponses, unknown, ThrowOnError> => (options.client ?? client).post<CancelVisitResponses, unknown, ThrowOnError>({ url: '/api/visits/{visitId}/cancel', ...options });

export const listStaff = <ThrowOnError extends boolean = false>(options?: Options<ListStaffData, ThrowOnError>): RequestResult<ListStaffResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListStaffResponses, unknown, ThrowOnError>({ url: '/api/staff', ...options });

export const createStaff = <ThrowOnError extends boolean = false>(options: Options<CreateStaffData, ThrowOnError>): RequestResult<CreateStaffResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateStaffResponses, unknown, ThrowOnError>({
    url: '/api/staff',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deactivateStaff = <ThrowOnError extends boolean = false>(options: Options<DeactivateStaffData, ThrowOnError>): RequestResult<DeactivateStaffResponses, unknown, ThrowOnError> => (options.client ?? client).post<DeactivateStaffResponses, unknown, ThrowOnError>({ url: '/api/staff/{id}/deactivate', ...options });

export const addTimeSlots = <ThrowOnError extends boolean = false>(options: Options<AddTimeSlotsData, ThrowOnError>): RequestResult<AddTimeSlotsResponses, unknown, ThrowOnError> => (options.client ?? client).post<AddTimeSlotsResponses, unknown, ThrowOnError>({
    url: '/api/schedules/{doctorId}/slots',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getMedicalHistory = <ThrowOnError extends boolean = false>(options: Options<GetMedicalHistoryData, ThrowOnError>): RequestResult<GetMedicalHistoryResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetMedicalHistoryResponses, unknown, ThrowOnError>({ url: '/api/patients/{patientId}/medical-records', ...options });

export const addMedicalRecord = <ThrowOnError extends boolean = false>(options: Options<AddMedicalRecordData, ThrowOnError>): RequestResult<AddMedicalRecordResponses, unknown, ThrowOnError> => (options.client ?? client).post<AddMedicalRecordResponses, unknown, ThrowOnError>({
    url: '/api/patients/{patientId}/medical-records',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>): RequestResult<RegisterResponses, unknown, ThrowOnError> => (options.client ?? client).post<RegisterResponses, unknown, ThrowOnError>({
    url: '/api/patients/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({ url: '/api/auth/logout', ...options });

export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, unknown, ThrowOnError> => (options.client ?? client).post<LoginResponses, unknown, ThrowOnError>({
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getVisitsByPatient = <ThrowOnError extends boolean = false>(options: Options<GetVisitsByPatientData, ThrowOnError>): RequestResult<GetVisitsByPatientResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetVisitsByPatientResponses, unknown, ThrowOnError>({ url: '/api/visits/patient/{patientId}', ...options });

export const getVisitsByDoctor = <ThrowOnError extends boolean = false>(options: Options<GetVisitsByDoctorData, ThrowOnError>): RequestResult<GetVisitsByDoctorResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetVisitsByDoctorResponses, unknown, ThrowOnError>({ url: '/api/visits/doctor/{doctorId}', ...options });

export const searchStaff = <ThrowOnError extends boolean = false>(options?: Options<SearchStaffData, ThrowOnError>): RequestResult<SearchStaffResponses, unknown, ThrowOnError> => (options?.client ?? client).get<SearchStaffResponses, unknown, ThrowOnError>({ url: '/api/staff/search', ...options });

export const getScheduleByDoctor = <ThrowOnError extends boolean = false>(options: Options<GetScheduleByDoctorData, ThrowOnError>): RequestResult<GetScheduleByDoctorResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetScheduleByDoctorResponses, unknown, ThrowOnError>({ url: '/api/schedules/doctor/{doctorId}', ...options });

export const getAvailableSlots = <ThrowOnError extends boolean = false>(options?: Options<GetAvailableSlotsData, ThrowOnError>): RequestResult<GetAvailableSlotsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAvailableSlotsResponses, unknown, ThrowOnError>({ url: '/api/schedules/available', ...options });

export const getMedicalRecordByVisitId = <ThrowOnError extends boolean = false>(options: Options<GetMedicalRecordByVisitIdData, ThrowOnError>): RequestResult<GetMedicalRecordByVisitIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetMedicalRecordByVisitIdResponses, unknown, ThrowOnError>({ url: '/api/patients/{patientId}/medical-records/visit/{visitId}', ...options });

export const searchPatients = <ThrowOnError extends boolean = false>(options?: Options<SearchPatientsData, ThrowOnError>): RequestResult<SearchPatientsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<SearchPatientsResponses, unknown, ThrowOnError>({ url: '/api/patients/search', ...options });

export const listDoctors = <ThrowOnError extends boolean = false>(options?: Options<ListDoctorsData, ThrowOnError>): RequestResult<ListDoctorsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListDoctorsResponses, unknown, ThrowOnError>({ url: '/api/doctors', ...options });

export const activate = <ThrowOnError extends boolean = false>(options: Options<ActivateData, ThrowOnError>): RequestResult<ActivateResponses, unknown, ThrowOnError> => (options.client ?? client).get<ActivateResponses, unknown, ThrowOnError>({ url: '/api/auth/activate', ...options });
