// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type UpdateStaffCommand = {
    firstName?: string;
    lastName?: string;
    email?: string;
    active?: boolean;
    specialization?: string;
    pwz?: string;
    department?: string;
    position?: string;
    workSchedule?: string;
};

export type TimeRange = {
    startTime?: string;
    endTime?: string;
};

export type UpdateSlotRequest = {
    timeRange?: TimeRange;
    office?: string;
};

export type UpdatePersonalDataReq = {
    firstName?: string;
    lastName?: string;
    phone?: string;
    email?: string;
    address?: string;
};

export type UpdateMedicalRecordReq = {
    diagnoses?: string;
    symptoms?: string;
    prescriptions?: string;
    notes?: string;
    testResults?: string;
};

export type ReserveVisitRequest = {
    patientId?: string;
    doctorId?: string;
    type?: 'GENERAL' | 'SPECIALIST' | 'FOLLOW_UP';
    slotIds?: Array<string>;
};

export type CreateStaffCommand = {
    role: 'DOCTOR' | 'ADMIN_STAFF';
    firstName?: string;
    lastName?: string;
    email?: string;
    specialization?: string;
    pwz?: string;
    department?: string;
    position?: string;
    workSchedule?: string;
};

export type AddSlotCommand = {
    timeRange?: TimeRange;
    office?: string;
};

export type AddSlotsRequest = {
    commands?: Array<AddSlotCommand>;
};

export type AddMedicalRecordReq = {
    visitId?: string;
    doctorId?: string;
    diagnoses?: string;
    symptoms?: string;
    prescriptions?: string;
    notes?: string;
    testResults?: string;
};

export type RegisterReq = {
    firstName?: string;
    lastName?: string;
    pesel?: string;
    phone?: string;
    email?: string;
    password?: string;
};

export type LoginRequest = {
    email?: string;
    password?: string;
};

export type AuthResult = {
    userId?: string;
    email?: string;
    role?: string;
    accessToken?: string;
};

export type VisitDto = {
    id?: string;
    date?: string;
    doctorId?: string;
    doctorName?: string;
    patientId?: string;
    patientName?: string;
    status?: string;
    type?: string;
    room?: string;
};

export type StaffDto = {
    id?: string;
    role?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    active?: boolean;
    specialization?: string;
    pwz?: string;
    department?: string;
    position?: string;
    workSchedule?: string;
};

export type ScheduleDto = {
    scheduleId?: string;
    doctorId?: string;
    slots?: Array<SlotDto>;
};

export type SlotDto = {
    slotId?: string;
    timeRange?: TimeRange;
    office?: string;
    status?: string;
};

export type AvailableSlotDto = {
    slotId?: string;
    doctorId?: string;
    doctorFirstName?: string;
    doctorLastName?: string;
    specialization?: string;
    startTime?: string;
    endTime?: string;
    office?: string;
};

export type DoctorId = {
    value?: string;
};

export type MedicalRecord = {
    recordId?: string;
    visitId?: string;
    doctorId?: DoctorId;
    createdAt?: string;
    diagnoses?: string;
    symptoms?: string;
    prescriptions?: string;
    notes?: string;
    testResults?: string;
    updatedAt?: string;
    updatedBy?: DoctorId;
};

export type Patient = {
    id?: PatientId;
    pesel?: string;
    medicalRecords?: Array<MedicalRecord>;
    firstName?: string;
    lastName?: string;
    phone?: string;
    email?: string;
    address?: string;
};

export type PatientId = {
    value?: string;
};

export type DeleteStaffData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/staff/{id}';
};

export type DeleteStaffResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetStaffData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/staff/{id}';
};

export type GetStaffResponses = {
    /**
     * OK
     */
    200: StaffDto;
};

export type GetStaffResponse = GetStaffResponses[keyof GetStaffResponses];

export type UpdateStaffData = {
    body: UpdateStaffCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/staff/{id}';
};

export type UpdateStaffResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RemoveSlotData = {
    body?: never;
    path: {
        doctorId: string;
        slotId: string;
    };
    query?: never;
    url: '/api/schedules/{doctorId}/slots/{slotId}';
};

export type RemoveSlotResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateSlotData = {
    body: UpdateSlotRequest;
    path: {
        doctorId: string;
        slotId: string;
    };
    query?: never;
    url: '/api/schedules/{doctorId}/slots/{slotId}';
};

export type UpdateSlotResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetPatientProfileData = {
    body?: never;
    path: {
        patientId: string;
    };
    query?: never;
    url: '/api/patients/{patientId}';
};

export type GetPatientProfileResponses = {
    /**
     * OK
     */
    200: Patient;
};

export type GetPatientProfileResponse = GetPatientProfileResponses[keyof GetPatientProfileResponses];

export type UpdatePersonalDataData = {
    body: UpdatePersonalDataReq;
    path: {
        patientId: string;
    };
    query?: never;
    url: '/api/patients/{patientId}';
};

export type UpdatePersonalDataResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type UpdatePersonalDataResponse = UpdatePersonalDataResponses[keyof UpdatePersonalDataResponses];

export type UpdateMedicalRecordData = {
    body: UpdateMedicalRecordReq;
    path: {
        patientId: string;
        recordId: string;
    };
    query?: never;
    url: '/api/patients/{patientId}/medical-records/{recordId}';
};

export type UpdateMedicalRecordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ReserveVisitData = {
    body: ReserveVisitRequest;
    path?: never;
    query?: never;
    url: '/api/visits';
};

export type ReserveVisitResponses = {
    /**
     * OK
     */
    200: string;
};

export type ReserveVisitResponse = ReserveVisitResponses[keyof ReserveVisitResponses];

export type CancelVisitData = {
    body?: never;
    path: {
        visitId: string;
    };
    query?: never;
    url: '/api/visits/{visitId}/cancel';
};

export type CancelVisitResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ListStaffData = {
    body?: never;
    path?: never;
    query?: {
        role?: string;
    };
    url: '/api/staff';
};

export type ListStaffResponses = {
    /**
     * OK
     */
    200: Array<StaffDto>;
};

export type ListStaffResponse = ListStaffResponses[keyof ListStaffResponses];

export type CreateStaffData = {
    body: CreateStaffCommand;
    path?: never;
    query?: never;
    url: '/api/staff';
};

export type CreateStaffResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type CreateStaffResponse = CreateStaffResponses[keyof CreateStaffResponses];

export type DeactivateStaffData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/staff/{id}/deactivate';
};

export type DeactivateStaffResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type AddTimeSlotsData = {
    body: AddSlotsRequest;
    path: {
        doctorId: string;
    };
    query?: never;
    url: '/api/schedules/{doctorId}/slots';
};

export type AddTimeSlotsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetMedicalHistoryData = {
    body?: never;
    path: {
        patientId: string;
    };
    query?: never;
    url: '/api/patients/{patientId}/medical-records';
};

export type GetMedicalHistoryResponses = {
    /**
     * OK
     */
    200: Array<MedicalRecord>;
};

export type GetMedicalHistoryResponse = GetMedicalHistoryResponses[keyof GetMedicalHistoryResponses];

export type AddMedicalRecordData = {
    body: AddMedicalRecordReq;
    path: {
        patientId: string;
    };
    query?: never;
    url: '/api/patients/{patientId}/medical-records';
};

export type AddMedicalRecordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RegisterData = {
    body: RegisterReq;
    path?: never;
    query?: never;
    url: '/api/patients/register';
};

export type RegisterResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LogoutData = {
    body?: never;
    headers?: {
        Authorization?: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: AuthResult;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type GetVisitsByPatientData = {
    body?: never;
    path: {
        patientId: string;
    };
    query?: {
        filter?: string;
        startDate?: string;
        endDate?: string;
        doctorId?: string;
        status?: string;
    };
    url: '/api/visits/patient/{patientId}';
};

export type GetVisitsByPatientResponses = {
    /**
     * OK
     */
    200: Array<VisitDto>;
};

export type GetVisitsByPatientResponse = GetVisitsByPatientResponses[keyof GetVisitsByPatientResponses];

export type GetVisitsByDoctorData = {
    body?: never;
    path: {
        doctorId: string;
    };
    query?: {
        filter?: string;
        startDate?: string;
        endDate?: string;
        patientId?: string;
        status?: string;
    };
    url: '/api/visits/doctor/{doctorId}';
};

export type GetVisitsByDoctorResponses = {
    /**
     * OK
     */
    200: Array<VisitDto>;
};

export type GetVisitsByDoctorResponse = GetVisitsByDoctorResponses[keyof GetVisitsByDoctorResponses];

export type SearchStaffData = {
    body?: never;
    path?: never;
    query?: {
        firstName?: string;
        lastName?: string;
        specialization?: string;
        role?: string;
        active?: boolean;
    };
    url: '/api/staff/search';
};

export type SearchStaffResponses = {
    /**
     * OK
     */
    200: Array<StaffDto>;
};

export type SearchStaffResponse = SearchStaffResponses[keyof SearchStaffResponses];

export type GetScheduleByDoctorData = {
    body?: never;
    path: {
        doctorId: string;
    };
    query?: {
        date?: string;
        from?: string;
        to?: string;
        status?: string;
    };
    url: '/api/schedules/doctor/{doctorId}';
};

export type GetScheduleByDoctorResponses = {
    /**
     * OK
     */
    200: ScheduleDto;
};

export type GetScheduleByDoctorResponse = GetScheduleByDoctorResponses[keyof GetScheduleByDoctorResponses];

export type GetAvailableSlotsData = {
    body?: never;
    path?: never;
    query?: {
        specialization?: string;
        doctorLastName?: string;
        from?: string;
        to?: string;
    };
    url: '/api/schedules/available';
};

export type GetAvailableSlotsResponses = {
    /**
     * OK
     */
    200: Array<AvailableSlotDto>;
};

export type GetAvailableSlotsResponse = GetAvailableSlotsResponses[keyof GetAvailableSlotsResponses];

export type GetMedicalRecordByVisitIdData = {
    body?: never;
    path: {
        patientId: string;
        visitId: string;
    };
    query?: never;
    url: '/api/patients/{patientId}/medical-records/visit/{visitId}';
};

export type GetMedicalRecordByVisitIdResponses = {
    /**
     * OK
     */
    200: MedicalRecord;
};

export type GetMedicalRecordByVisitIdResponse = GetMedicalRecordByVisitIdResponses[keyof GetMedicalRecordByVisitIdResponses];

export type SearchPatientsData = {
    body?: never;
    path?: never;
    query?: {
        firstName?: string;
        lastName?: string;
        pesel?: string;
        patientCardNumber?: string;
    };
    url: '/api/patients/search';
};

export type SearchPatientsResponses = {
    /**
     * OK
     */
    200: Array<Patient>;
};

export type SearchPatientsResponse = SearchPatientsResponses[keyof SearchPatientsResponses];

export type ListDoctorsData = {
    body?: never;
    path?: never;
    query?: {
        specialization?: string;
        name?: string;
    };
    url: '/api/doctors';
};

export type ListDoctorsResponses = {
    /**
     * OK
     */
    200: Array<StaffDto>;
};

export type ListDoctorsResponse = ListDoctorsResponses[keyof ListDoctorsResponses];

export type ActivateData = {
    body?: never;
    path?: never;
    query: {
        token: string;
    };
    url: '/api/auth/activate';
};

export type ActivateResponses = {
    /**
     * OK
     */
    200: unknown;
};
